default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: your_username
  password: your_password
  host: localhost

development:
  <<: *default
  database: jarchive_development

test:
  <<: *default
  database: jarchive_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
